name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Load .env file
        run: |
          if [ -f .env ]; then
            export $(cat .env | xargs)
          fi

      - name: Extract Version
        run: echo "VERSION=$(grep -oP '(?<=__version__ = \")(.+)(?=\")' app/__init__.py)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ env.VERSION }} .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}:${{ env.VERSION }}

